### PR TITLE
Position float

### PR DESCRIPTION
**Pull request by errea**
This pull request was meant to implement the Positioning-float element project.

The following were the requirements
=> Use flexbox to position elements on the screen
=> header, central column with the main content, 
=> grid-like content in the middle, bottom content, and footer.
This project is a clone of a New York Times article page.

Concepts Applied to the project:
1. Embedding images
2. The box model
3. Flexbox
4. Positioning and Grid layout in CSS

Approve to Create the project 
1. Create HTML mark-up.
I thought about all the elements on the page and how they are grouped together and applied the concepts I learned.
2. Layout the basic structure of the page using empty semantic HTML elements that are appropriately sized and positioned. 
3.  Made the colors, fonts, and images used. 
4. I used my browser’s developer tools as one of the concepts I learned and set up the top navigation bar. 
5. Push your solution to GitHub. 
@MahmoudBakr23 Thank you for your review
Fixes #

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there 👋 Great work you've done so far on this project. You've created a perfect README file, followed the Git Flow Guidelines, and most importantly! You've succeeded in creating a very similar page to the original one with all of the project specifications 😊❤✔ , However, there are still a few changes to make in order to get it approved.

- [x] Please write a descriptive Pull Request (PR) summary for your project. (Give yourself a reminder through this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- [x] Please fill your README file's empty sections with appropriate details in each.

<hr>

Kindly get those done and you'll be good to go 😊🙏
Good luck with the next and happy coding 👨‍💻💻

**Comment by errea** [comment]
Seen and done the changes as requested

**Review by errea — COMMENTED** [review]
@MahmoudBakr23 I guess I did what you asked of me. Thank you for your feedback.

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @errea 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes 👇.
- [x] Please resolve the conflicts from the README file.
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by errea** [comment]
Fixed merging conflicts in readme file

**Review by teekaytech — CHANGES_REQUESTED** [review]
### Status: Approved :green_circle: 

**Congratulations @errea, this project has passed all the mandatory requirements. It is therefore approved :heavy_check_mark:**

**[OPTIONAL CHANGES]**
_Although the project is approved, these changes will make your webpage look better._
- In subsequent commits, let your commit messages be more descriptive. [Check this article](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8) to know more. A message like `modified index.html` is not the best.
- Check the image below and make necessary changes.
img


Again, congratulations, you can merge to the main/master branch.
Do not forget to fill the project completion form
Good luck with your next task.

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Pull request merged**
